### PR TITLE
apollo: Correct TARGET_ARCH

### PR DESCRIPTION
**Pull request by roynatech2544**

### CODE REVIEW

**Comment by FPSensor** [comment]
looks interesting but why using arm as main arch
ig better use x86_64 as first and arm64 as seccond or at last use arm64 as first but arm is deprecated already so you will destroy the perf of the ppl

**Comment by FPSensor** [comment]
if u say why arm best af to get 99999999FPS in PUBG i will merge

**Comment by roynatech2544** [comment]
Ban

**Comment by FPSensor** [comment]
make it on new branch

**Comment by roynatech2544** [comment]
Hi

**Comment by FPSensor** [comment]
Hi
How are u?
ROM booted?

**Comment by roynatech2544** [comment]
a

**Pull request closed without merging**
